import { PrismaClient, QuestionDifficulty } from '@prisma/client';

export async function seedQuestions(prisma: PrismaClient) {
  console.log('🌱 Seeding questions...');

  const flightTheory = await prisma.subject.findUnique({
    where: {
      slug: 'flight-theory'
    }
  });

  const meteorology = await prisma.subject.findUnique({
    where: {
      slug: 'meteorology'
    }
  });


  if (!flightTheory || !meteorology) {
    throw new Error('Required subjects not found.');
  }


  await prisma.question.createMany({
    data: []
  });


  const questions = [

    {
      subjectId: flightTheory.id,
      statement: 'What is the primary force responsible for keeping an aircraft in the air?',
      explanation: 'Lift is generated by the pressure difference between the upper and lower surfaces of the wing.',
      difficulty: QuestionDifficulty.EASY,
      alternatives: [
        ['A', 'Lift generated by pressure difference.', true],
        ['B', 'Engine thrust.', false],
        ['C', 'Aircraft weight.', false],
        ['D', 'Centrifugal force.', false],
      ]
    },

    {
      subjectId: flightTheory.id,
      statement: 'Which aircraft component generates most of the lift?',
      explanation: 'The wings generate lift through aerodynamic forces.',
      difficulty: QuestionDifficulty.EASY,
      alternatives: [
        ['A', 'Engine.', false],
        ['B', 'Wing.', true],
        ['C', 'Landing gear.', false],
        ['D', 'Rudder.', false],
      ]
    },

    {
      subjectId: flightTheory.id,
      statement: 'What force opposes aircraft movement through the air?',
      explanation: 'Drag acts opposite to the direction of motion.',
      difficulty: QuestionDifficulty.MEDIUM,
      alternatives: [
        ['A', 'Lift.', false],
        ['B', 'Drag.', true],
        ['C', 'Weight.', false],
        ['D', 'Thrust.', false],
      ]
    },

    {
      subjectId: flightTheory.id,
      statement: 'What is the purpose of aircraft flaps?',
      explanation: 'Flaps increase lift and drag during low-speed operations.',
      difficulty: QuestionDifficulty.MEDIUM,
      alternatives: [
        ['A', 'Increase lift at low speeds.', true],
        ['B', 'Increase engine power.', false],
        ['C', 'Reduce fuel consumption.', false],
        ['D', 'Control yaw.', false],
      ]
    },

    {
      subjectId: flightTheory.id,
      statement: 'Which axis controls aircraft pitch movement?',
      explanation: 'Pitch movement occurs around the lateral axis.',
      difficulty: QuestionDifficulty.HARD,
      alternatives: [
        ['A', 'Longitudinal axis.', false],
        ['B', 'Vertical axis.', false],
        ['C', 'Lateral axis.', true],
        ['D', 'Engine axis.', false],
      ]
    },


    {
      subjectId: meteorology.id,
      statement: 'Which cloud type is most commonly associated with thunderstorms?',
      explanation: 'Cumulonimbus clouds are associated with thunderstorms.',
      difficulty: QuestionDifficulty.MEDIUM,
      alternatives: [
        ['A', 'Cirrus.', false],
        ['B', 'Stratus.', false],
        ['C', 'Cumulonimbus.', true],
        ['D', 'Altostratus.', false],
      ]
    },

    {
      subjectId: meteorology.id,
      statement: 'What instrument measures atmospheric pressure?',
      explanation: 'The barometer measures atmospheric pressure.',
      difficulty: QuestionDifficulty.EASY,
      alternatives: [
        ['A', 'Barometer.', true],
        ['B', 'Altimeter.', false],
        ['C', 'Airspeed indicator.', false],
        ['D', 'Compass.', false],
      ]
    }

  ];


  for (const question of questions) {

    await prisma.question.create({
      data: {
        subjectId: question.subjectId,
        statement: question.statement,
        explanation: question.explanation,
        difficulty: question.difficulty,

        alternatives: {
          create: question.alternatives.map(([letter, content, isCorrect]) => ({
            letter: letter as string,
            content: content as string,
            isCorrect: isCorrect as boolean
          }))
        }
      }
    });

  }


  console.log('✅ Questions seeded');
}