import { PrismaClient, QuestionDifficulty } from '@prisma/client';

export async function seedQuestions(prisma: PrismaClient) {
  console.log('🌱 Seeding questions...');

  const flightTheory = await prisma.subject.findUnique({
    where: {
      slug: 'flight-theory'
    }
  });

  const meteorology = await prisma.subject.findUnique({
    where: {
      slug: 'meteorology'
    }
  });

  if (!flightTheory || !meteorology) {
    throw new Error('Required subjects not found.');
  }

  await prisma.question.create({
    data: {
      subjectId: flightTheory.id,
      statement: 'What is the primary force responsible for keeping an aircraft in the air?',
      explanation: 'Lift is generated by the pressure difference between the upper and lower surfaces of the wing.',
      difficulty: QuestionDifficulty.EASY,

      alternatives: {
        create: [
          {
            letter: 'A',
            content: 'Lift generated by pressure difference.',
            isCorrect: true
          },
          {
            letter: 'B',
            content: 'Engine thrust.',
            isCorrect: false
          },
          {
            letter: 'C',
            content: 'Aircraft weight.',
            isCorrect: false
          },
          {
            letter: 'D',
            content: 'Centrifugal force.',
            isCorrect: false
          }
        ]
      }
    }
  });

  await prisma.question.create({
    data: {
      subjectId: meteorology.id,
      statement: 'Which cloud type is most commonly associated with thunderstorms?',
      explanation: 'Cumulonimbus clouds are associated with thunderstorms, heavy rain, turbulence and icing.',
      difficulty: QuestionDifficulty.MEDIUM,

      alternatives: {
        create: [
          {
            letter: 'A',
            content: 'Cirrus.',
            isCorrect: false
          },
          {
            letter: 'B',
            content: 'Stratus.',
            isCorrect: false
          },
          {
            letter: 'C',
            content: 'Cumulonimbus.',
            isCorrect: true
          },
          {
            letter: 'D',
            content: 'Altostratus.',
            isCorrect: false
          }
        ]
      }
    }
  });

  console.log('✅ Questions seeded');
}