import { ApiProperty } from '@nestjs/swagger';
import { IsBoolean, IsNotEmpty, IsString, Length } from 'class-validator';

export class CreateQuestionAlternativeDto {

  @ApiProperty({
    example: 'A',
    description: 'Alternative letter.'
  })
  @IsString()
  @Length(1, 1)
  letter!: string;

  @ApiProperty({
    example: 'Lift is generated by pressure difference.',
    description: 'Alternative content.'
  })
  @IsString()
  @IsNotEmpty()
  content!: string;

  @ApiProperty({
    example: false,
    description: 'Indicates whether this is the correct alternative.'
  })
  @IsBoolean()
  isCorrect!: boolean;

}